// Lista padrão de insumos usada como seed inicial para novos usuários.
// Pode ser importada tanto pelo servidor (API) quanto pelo cliente.

export interface InsumoSeed {
  insumoId: string;
  nome: string;
  unidade: string;
  categoriaId: string;
  categoriaNome: string;
  categoriaIcone: string;
}

const MATERIAS_PRIMAS: Omit<InsumoSeed, 'categoriaId' | 'categoriaNome' | 'categoriaIcone'>[] = [
  { insumoId: 'abacaxi',               nome: 'ABACAXI',                     unidade: 'un' },
  { insumoId: 'acucar',                nome: 'AÇÚCAR',                      unidade: 'kg' },
  { insumoId: 'alho-moido',            nome: 'ALHO MOÍDO',                  unidade: 'kg' },
  { insumoId: 'alho-crocante',         nome: 'ALHO CROCANTE',               unidade: 'kg' },
  { insumoId: 'amaciante-carne',       nome: 'AMACIANTE DE CARNE',          unidade: 'kg' },
  { insumoId: 'aneis-cebola',          nome: 'ANÉIS DE CEBOLA',             unidade: 'kg' },
  { insumoId: 'amendoim-granulado',    nome: 'AMENDOIM GRANULADO',          unidade: 'kg' },
  { insumoId: 'ameixa',                nome: 'AMEIXA',                      unidade: 'kg' },
  { insumoId: 'atum-lata',             nome: 'ATUM LATA',                   unidade: 'un' },
  { insumoId: 'azeite-oliva',          nome: 'AZEITE DE OLIVA',             unidade: 'L'  },
  { insumoId: 'azeitona-preta',        nome: 'AZEITONA PRETA',              unidade: 'kg' },
  { insumoId: 'azeitona-verde',        nome: 'AZEITONA VERDE',              unidade: 'kg' },
  { insumoId: 'bacon-cru',             nome: 'BACON (CRU)',                 unidade: 'kg' },
  { insumoId: 'banana',                nome: 'BANANA',                      unidade: 'kg' },
  { insumoId: 'barbecue',              nome: 'BARBECUE',                    unidade: 'kg' },
  { insumoId: 'batata-palha',          nome: 'BATATA PALHA',                unidade: 'kg' },
  { insumoId: 'batata-sorriso',        nome: 'BATATA SORRISO',              unidade: 'kg' },
  { insumoId: 'berinjela-crua',        nome: 'BERINJELA (CRUA)',            unidade: 'kg' },
  { insumoId: 'bolacha-negresco',      nome: 'BOLACHA NEGRESCO',            unidade: 'un' },
  { insumoId: 'biscoito-kitkat',       nome: 'BISCOITO KIT KAT',            unidade: 'un' },
  { insumoId: 'brocolis',              nome: 'BRÓCOLIS',                    unidade: 'kg' },
  { insumoId: 'camarao',               nome: 'CAMARÃO',                     unidade: 'kg' },
  { insumoId: 'canela',                nome: 'CANELA',                      unidade: 'kg' },
  { insumoId: 'carne-isca-strogonoff', nome: 'CARNE EM ISCA (STROGONOFF)', unidade: 'kg' },
  { insumoId: 'carne-moida-bolonhesa', nome: 'CARNE MOÍDA (BOLONHESA)',     unidade: 'kg' },
  { insumoId: 'catchup-galao',         nome: 'CATCHUP GALÃO',               unidade: 'un' },
  { insumoId: 'catchup-sache',         nome: 'CATCHUP SACHE',               unidade: 'un' },
  { insumoId: 'cebola',                nome: 'CEBOLA',                      unidade: 'kg' },
  { insumoId: 'cebola-crocante',       nome: 'CEBOLA CROCANTE',             unidade: 'kg' },
  { insumoId: 'cereja',                nome: 'CEREJA',                      unidade: 'kg' },
  { insumoId: 'champignon',            nome: 'CHAMPIGNON',                  unidade: 'kg' },
  { insumoId: 'chocolate-branco',      nome: 'CHOCOLATE BRANCO',            unidade: 'kg' },
  { insumoId: 'chocolate-preto',       nome: 'CHOCOLATE PRETO',             unidade: 'kg' },
  { insumoId: 'coco-ralado',           nome: 'COCO RALADO',                 unidade: 'kg' },
  { insumoId: 'confete',               nome: 'CONFETE',                     unidade: 'un' },
  { insumoId: 'creme-leite',           nome: 'CREME DE LEITE',              unidade: 'un' },
  { insumoId: 'creme-beijinho',        nome: 'CREME BEIJINHO',              unidade: 'kg' },
  { insumoId: 'creme-pistache',        nome: 'CREME PISTACHE',              unidade: 'kg' },
  { insumoId: 'creme-culinario',       nome: 'CREME CULINÁRIO',             unidade: 'kg' },
  { insumoId: 'creme-galak',           nome: 'CREME GALAK',                 unidade: 'kg' },
  { insumoId: 'creme-kitkat',          nome: 'CREME KIT KAT',               unidade: 'kg' },
  { insumoId: 'costela',               nome: 'COSTELA',                     unidade: 'kg' },
  { insumoId: 'doce-leite',            nome: 'DOCE DE LEITE',               unidade: 'kg' },
  { insumoId: 'ervilha',               nome: 'ERVILHA',                     unidade: 'kg' },
  { insumoId: 'escarola-crua',         nome: 'ESCAROLA (CRUA)',             unidade: 'kg' },
  { insumoId: 'doritos',               nome: 'DORITOS',                     unidade: 'un' },
  { insumoId: 'farinha-trigo',         nome: 'FARINHA DE TRIGO',            unidade: 'kg' },
  { insumoId: 'fermento-biologico',    nome: 'FERMENTO BIOLÓGICO',          unidade: 'kg' },
  { insumoId: 'figo-calda',            nome: 'FIGO EM CALDA',               unidade: 'kg' },
  { insumoId: 'file-peito-sem-osso',   nome: 'FILÉ DE PEITO SEM OSSO',      unidade: 'kg' },
  { insumoId: 'lemon-pepper',          nome: 'LEMON PEPPER',                unidade: 'kg' },
  { insumoId: 'linguica-calabresa',    nome: 'LINGUIÇA CALABRESA',          unidade: 'kg' },
  { insumoId: 'lombo',                 nome: 'LOMBO',                       unidade: 'kg' },
  { insumoId: 'maionese-sache',        nome: 'MAIONESE SACHE',              unidade: 'un' },
  { insumoId: 'manjericao-italiano',   nome: 'MANJERICÃO ITALIANO',         unidade: 'kg' },
  { insumoId: 'margarina',             nome: 'MARGARINA',                   unidade: 'kg' },
  { insumoId: 'milho',                 nome: 'MILHO',                       unidade: 'kg' },
  { insumoId: 'molho-pizza',           nome: 'MOLHO PIZZA',                 unidade: 'kg' },
  { insumoId: 'molho-tomodoro',        nome: 'MOLHO TOMODORO',              unidade: 'kg' },
  { insumoId: 'morango',               nome: 'MORANGO',                     unidade: 'kg' },
  { insumoId: 'mostarda-galao',        nome: 'MOSTARDA GALÃO',              unidade: 'un' },
  { insumoId: 'mostarda-sache',        nome: 'MOSTARDA SACHE',              unidade: 'un' },
  { insumoId: 'molho-pimenta-sache',   nome: 'MOLHO PIMENTA SACHE',         unidade: 'un' },
  { insumoId: 'oleo',                  nome: 'ÓLEO',                        unidade: 'L'  },
  { insumoId: 'oregano',               nome: 'ORÉGANO',                     unidade: 'kg' },
  { insumoId: 'ovos',                  nome: 'OVOS',                        unidade: 'un' },
  { insumoId: 'palmito',               nome: 'PALMITO',                     unidade: 'kg' },
  { insumoId: 'pepperoni',             nome: 'PEPPERONI',                   unidade: 'kg' },
  { insumoId: 'pessego-calda',         nome: 'PÊSSEGO EM CALDA',            unidade: 'kg' },
  { insumoId: 'pimenta-calabresa',     nome: 'PIMENTA CALABRESA',           unidade: 'kg' },
  { insumoId: 'pimentao-verde',        nome: 'PIMENTÃO VERDE',              unidade: 'kg' },
  { insumoId: 'pasta-alho',            nome: 'PASTA DE ALHO',               unidade: 'kg' },
  { insumoId: 'presunto',              nome: 'PRESUNTO',                    unidade: 'kg' },
  { insumoId: 'queijo-catupiry',       nome: 'QUEIJO CATUPIRY',             unidade: 'kg' },
  { insumoId: 'queijo-cheddar',        nome: 'QUEIJO CHEDDAR',              unidade: 'kg' },
  { insumoId: 'queijo-gorgonzola',     nome: 'QUEIJO GORGONZOLA',           unidade: 'kg' },
  { insumoId: 'queijo-mussarela',      nome: 'QUEIJO MUSSARELA',            unidade: 'kg' },
  { insumoId: 'queijo-cream-cheese',   nome: 'QUEIJO CREAM CHEESE',         unidade: 'kg' },
  { insumoId: 'queijo-parmesao',       nome: 'QUEIJO PARMESÃO',             unidade: 'kg' },
  { insumoId: 'queijo-provolone',      nome: 'QUEIJO PROVOLONE',            unidade: 'kg' },
  { insumoId: 'queijo-ricota',         nome: 'QUEIJO RICOTA',               unidade: 'kg' },
  { insumoId: 'rucula',                nome: 'RÚCULA',                      unidade: 'kg' },
  { insumoId: 'sal',                   nome: 'SAL',                         unidade: 'kg' },
  { insumoId: 'salame-italiano',       nome: 'SALAME ITALIANO',             unidade: 'kg' },
  { insumoId: 'semola',                nome: 'SÊMOLA',                      unidade: 'kg' },
  { insumoId: 'tempero-completo',      nome: 'TEMPERO COMPLETO',            unidade: 'kg' },
  { insumoId: 'tomate',                nome: 'TOMATE',                      unidade: 'kg' },
  { insumoId: 'tomate-seco',           nome: 'TOMATE SECO',                 unidade: 'kg' },
  { insumoId: 'tomate-cereja',         nome: 'TOMATE CEREJA',               unidade: 'kg' },
  { insumoId: 'uva-passas',            nome: 'UVA PASSAS',                  unidade: 'kg' },
  { insumoId: 'vinagre',               nome: 'VINAGRE',                     unidade: 'L'  },
];

const EMBALAGENS: Omit<InsumoSeed, 'categoriaId' | 'categoriaNome' | 'categoriaIcone'>[] = [
  { insumoId: 'embalagem-20',       nome: 'EMBALAGEM 20',       unidade: 'un' },
  { insumoId: 'embalagem-25',       nome: 'EMBALAGEM 25',       unidade: 'un' },
  { insumoId: 'embalagem-30',       nome: 'EMBALAGEM 30',       unidade: 'un' },
  { insumoId: 'embalagem-35',       nome: 'EMBALAGEM 35',       unidade: 'un' },
  { insumoId: 'embalagem-40',       nome: 'EMBALAGEM 40',       unidade: 'un' },
  { insumoId: 'embalagem-calzone',  nome: 'EMBALAGEM CALZONE',  unidade: 'un' },
  { insumoId: 'embalagem-entradas', nome: 'EMBALAGEM ENTRADAS', unidade: 'un' },
  { insumoId: 'mesinha',            nome: 'MESINHA',            unidade: 'un' },
  { insumoId: 'separador',          nome: 'SEPARADOR',          unidade: 'un' },
];

const BEBIDAS: Omit<InsumoSeed, 'categoriaId' | 'categoriaNome' | 'categoriaIcone'>[] = [
  { insumoId: 'agua-com-gas',                  nome: 'ÁGUA COM GÁS',                    unidade: 'un' },
  { insumoId: 'agua-sem-gas',                  nome: 'ÁGUA SEM GÁS',                    unidade: 'un' },
  { insumoId: 'cerveja-sol',                   nome: 'CERVEJA SOL',                     unidade: 'un' },
  { insumoId: 'energetico',                    nome: 'ENERGÉTICO',                      unidade: 'un' },
  { insumoId: 'cerveja-heineken-long-neck',    nome: 'CERVEJA HEINEKEN LONG NECK',      unidade: 'un' },
  { insumoId: 'cha-limao-15',                  nome: 'CHÁ LIMÃO 1,5',                   unidade: 'un' },
  { insumoId: 'cha-pessego-15',                nome: 'CHÁ PÊSSEGO 1,5',                 unidade: 'un' },
  { insumoId: 'coca-lata',                     nome: 'COCA LATA',                       unidade: 'un' },
  { insumoId: 'coca-lata-zero',                nome: 'COCA LATA ZERO',                  unidade: 'un' },
  { insumoId: 'coca-600',                      nome: 'COCA 600',                        unidade: 'un' },
  { insumoId: 'coca-600-zero',                 nome: 'COCA 600 ZERO',                   unidade: 'un' },
  { insumoId: 'coca-1litro',                   nome: 'COCA 1 LITRO',                    unidade: 'un' },
  { insumoId: 'coca-1litro-zero',              nome: 'COCA 1 LITRO ZERO',               unidade: 'un' },
  { insumoId: 'coca-2litros',                  nome: 'COCA 2 LITROS',                   unidade: 'un' },
  { insumoId: 'coca-2litros-zero',             nome: 'COCA 2 LITROS ZERO',              unidade: 'un' },
  { insumoId: 'fanta-guarana-lata',            nome: 'FANTA GUARANÁ LATA',              unidade: 'un' },
  { insumoId: 'fanta-guarana-2l',              nome: 'FANTA GUARANÁ 2 LITROS',          unidade: 'un' },
  { insumoId: 'fanta-guarana-zero-2l',         nome: 'FANTA GUARANÁ ZERO 2 LITROS',     unidade: 'un' },
  { insumoId: 'fanta-laranja-lata',            nome: 'FANTA LARANJA LATA',              unidade: 'un' },
  { insumoId: 'fanta-laranja-2l',              nome: 'FANTA LARANJA 2 LITROS',          unidade: 'un' },
  { insumoId: 'kuat-lata',                     nome: 'KUAT LATA',                       unidade: 'un' },
  { insumoId: 'kuat-2l',                       nome: 'KUAT 2 LITROS',                   unidade: 'un' },
  { insumoId: 'kuat-2l-zero',                  nome: 'KUAT 2 LITROS ZERO',              unidade: 'un' },
  { insumoId: 'sprite-2l',                     nome: 'SPRITE 2 LITROS',                 unidade: 'un' },
  { insumoId: 'suco-maracuja',                 nome: 'SUCO MARACUJÁ',                   unidade: 'un' },
  { insumoId: 'suco-manga',                    nome: 'SUCO DE MANGA',                   unidade: 'un' },
  { insumoId: 'suco-pessego',                  nome: 'SUCO PÊSSEGO',                    unidade: 'un' },
  { insumoId: 'suco-uva',                      nome: 'SUCO UVA',                        unidade: 'un' },
  { insumoId: 'suco-integral-uva-15',          nome: 'SUCO INTEGRAL UVA 1,5',           unidade: 'un' },
  { insumoId: 'tonica',                        nome: 'TÔNICA',                          unidade: 'un' },
  { insumoId: 'suco-laranja-900ml',            nome: 'SUCO DE LARANJA 900 ML',          unidade: 'un' },
  { insumoId: 'suco-abacaxi-900ml',            nome: 'SUCO DE ABACAXI 900 ML',          unidade: 'un' },
  { insumoId: 'cerveja-becks-lata',            nome: 'CERVEJA BECKS LATA',              unidade: 'un' },
  { insumoId: 'cerveja-becks-long-neck',       nome: 'CERVEJA BECKS LONG NECK',         unidade: 'un' },
  { insumoId: 'cerveja-budweiser-lata',        nome: 'CERVEJA BUDWEISER LATA',          unidade: 'un' },
  { insumoId: 'cerveja-spaten-long-neck',      nome: 'CERVEJA SPATEN LONG NECK',        unidade: 'un' },
  { insumoId: 'cerveja-spaten-lata',           nome: 'CERVEJA SPATEN LATA',             unidade: 'un' },
  { insumoId: 'cerveja-budweiser-long-neck',   nome: 'CERVEJA BUDWEISER LONG NECK',     unidade: 'un' },
  { insumoId: 'cerveja-original-lata',         nome: 'CERVEJA ORIGINAL LATA',           unidade: 'un' },
  { insumoId: 'cerveja-original-long-neck',    nome: 'CERVEJA ORIGINAL LONG NECK',      unidade: 'un' },
  { insumoId: 'cerveja-stella-lata',           nome: 'CERVEJA STELLA ARTOIS LATA',      unidade: 'un' },
  { insumoId: 'cerveja-stella-long-neck',      nome: 'CERVEJA STELLA ARTOIS LONG NECK', unidade: 'un' },
  { insumoId: 'guarana-antarctica-lata',       nome: 'GUARANÁ ANTÁRCTICA LATA',         unidade: 'un' },
  { insumoId: 'guarana-antarctica-lata-zero',  nome: 'GUARANÁ ANTÁRCTICA LATA ZERO',    unidade: 'un' },
  { insumoId: 'guarana-antarctica-600',        nome: 'GUARANÁ ANTÁRCTICA 600',          unidade: 'un' },
  { insumoId: 'guarana-antarctica-200',        nome: 'GUARANÁ ANTÁRCTICA 200',          unidade: 'un' },
  { insumoId: 'guarana-antarctica-2l',         nome: 'GUARANÁ ANTÁRCTICA 2L',           unidade: 'un' },
  { insumoId: 'guarana-antarctica-2l-zero',    nome: 'GUARANÁ ANTÁRCTICA 2L ZERO',      unidade: 'un' },
  { insumoId: 'pepsi-lata',                    nome: 'PEPSI LATA',                      unidade: 'un' },
  { insumoId: 'pepsi-lata-zero',               nome: 'PEPSI LATA ZERO',                 unidade: 'un' },
  { insumoId: 'pepsi-600',                     nome: 'PEPSI 600',                       unidade: 'un' },
  { insumoId: 'guarana-antarctica-600-zero',   nome: 'GUARANÁ ANTÁRCTICA 600 ZERO',     unidade: 'un' },
  { insumoId: 'pepsi-2l',                      nome: 'PEPSI 2L',                        unidade: 'un' },
  { insumoId: 'pepsi-2l-zero',                 nome: 'PEPSI 2L ZERO',                   unidade: 'un' },
  { insumoId: 'soda',                          nome: 'SODA',                            unidade: 'un' },
  { insumoId: 'powerade',                      nome: 'POWERADE',                        unidade: 'un' },
];

export const CATEGORIAS_PADRAO = [
  { id: 'materias-primas', nome: 'Matéria Prima', icone: '🧂' },
  { id: 'embalagens',      nome: 'Embalagens',    icone: '📦' },
  { id: 'bebidas',         nome: 'Bebidas',        icone: '🥤' },
  { id: 'receitas',        nome: 'Receitas',       icone: '📋' },
] as const;

export const INSUMOS_PADRAO: InsumoSeed[] = [
  ...MATERIAS_PRIMAS.map(p => ({
    ...p,
    categoriaId: 'materias-primas',
    categoriaNome: 'Matéria Prima',
    categoriaIcone: '🧂',
  })),
  ...EMBALAGENS.map(p => ({
    ...p,
    categoriaId: 'embalagens',
    categoriaNome: 'Embalagens',
    categoriaIcone: '📦',
  })),
  ...BEBIDAS.map(p => ({
    ...p,
    categoriaId: 'bebidas',
    categoriaNome: 'Bebidas',
    categoriaIcone: '🥤',
  })),
];
